---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    rule_files:
    - alert.rules
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093
    scrape_configs:
      - job_name: 'node_exporter'
        static_configs:
          - targets: ['10.250.2.5:9100', '10.250.2.4:9100']
        relabel_configs:
        - source_labels: [__address__]
          target_label: instance
          regex: "([^:]+).*"
          replacement: '${1}'
  alert.rules: |
    groups:
    - name: selinux status
      rules:
      - alert: selinux disabled
        expr: node_selinux_current_mode == 0
        for: 10s
        labels:
          severity: page
        annotations:
          summary: "selinx disabled"
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
    route:
      group_by: ['alertname']
      group_wait: 5s
      group_interval: 30s
      repeat_interval: 10m
      receiver: 'EDA'
    receivers:
    - name: 'EDA'
      webhook_configs:
      - url: 'http://10.250.2.6:5050'
---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  containers:
  - name: prometheus
    image: docker.io/prom/prometheus:latest
    args:
    - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
    - containerPort: 9090
      hostPort: 9090
      protocol: TCP
    volumeMounts:
    - name: prometheus
      mountPath: /etc/prometheus/prometheus.yml
      subPath: prometheus.yml
    - name: prometheus
      mountPath: /etc/prometheus/alert.rules
      subPath: alert.rules
  - name: alertmanager
    image: docker.io/prom/alertmanager:latest
    args:
    - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
    - containerPort: 9093
      hostPort: 9093
      protocol: TCP
    volumeMounts:
    - name: prometheus
      mountPath: /etc/alertmanager/alertmanager.yml
      subPath: alertmanager.yml
  restartPolicy: Always
  dnsPolicy: Default
  volumes:
  - name: prometheus
    configMap:
      name: prometheus
